module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'refactor',
        'docs',
        'style',
        'test',
        'build',
        'config',
        'chore',
        'ci',
        'revert',
        'security',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'server',
        'routes',
        'services',
        'config',
        'models',
        'auth',
        'ai',
        'rag',
        'docker',
        'ci',
        'deps',
        'deps-dev',
        'tests',
        'frontend',
        'logging',
        'security',
        'setup',
        'docs',
      ],
    ],
    'header-max-length': [2, 'always', 120],
    'body-max-line-length': [1, 'always', 200],
  },
  ignores: [
    (message) => /^Merge/.test(message),
    (message) => /^Revert/.test(message),
    (message) => /^Bumps/.test(message),
  ],
};
